# Generated by Django 3.2.5 on 2021-07-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('total_services', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
