# Generated by Django 3.2.5 on 2021-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210804_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
