# Generated by Django 3.2.5 on 2021-08-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210804_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='real',
        ),
    ]
