# Generated by Django 3.2.5 on 2021-08-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210806_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='init_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
