# Generated by Django 3.2.5 on 2021-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210812_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
