# Generated by Django 3.2.5 on 2021-08-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productstock_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='stock_real',
            new_name='real_stock',
        ),
        migrations.AlterField(
            model_name='productentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_entry', to='product.productstock'),
        ),
    ]
