# Generated by Django 3.2.5 on 2021-08-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210815_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
