# Generated by Django 3.2.5 on 2021-08-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productstock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productstock',
            name='medium_value',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='minium_value',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
