# Generated by Django 3.2.5 on 2021-08-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210820_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='stock_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
