# Generated by Django 3.2.5 on 2021-07-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceproductdetail',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_products', to='service.service'),
        ),
    ]
