# Generated by Django 3.2.5 on 2021-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210717_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='state',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
