# Generated by Django 3.2.5 on 2021-08-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('service', '0004_alter_service_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproductdetail',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
