# Generated by Django 3.2.5 on 2021-08-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210806_1740'),
        ('service', '0006_serviceproductdetail_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproductdetail',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
