# Generated by Django 3.2.5 on 2021-08-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210815_2314'),
        ('service', '0008_alter_serviceproductdetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproductdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productstock'),
        ),
    ]
